os:
    - linux
language: cpp
sudo: enabled
addons:
    apt:
        packages:
            - ocl-icd-opencl-dev
script:
    - cmake .
    - make SOFTENG-751-Assignment-ParaStats
    - make SOFTENG-751-Assignment-ParaStats-Test
    - ./SOFTENG-751-Assignment-ParaStats-Test TRAVIS
notifications:
    slack:
        rooms:
          - parastats:7DSnysk6wGWgnw0zFVSjEKvS#travis
        on_success: change
        on_failure: always
