language: cpp
sudo: enabled
before_install:
- sudo apt update -qq
- sudo apt install -qq ocl-icd-opencl-dev
script: cmake -DCMAKE_BUILD_TYPE= -G "CodeBlocks - Unix Makefiles"
notifications:
    slack:
        rooms:
          - parastats:7DSnysk6wGWgnw0zFVSjEKvS#travis
        on_success: change
        on_failure: always
